resolver: lts-14.2

packages:
- identifiers
- multiline
- render
- web-browser
- web-url
- web

extra-deps:
- boomerang-1.4.5.6
- rapid-0.1.4
- git: https://github.com/eyeinsky/fixedlist.git
  commit: 8e88d82218fee3716313568b5c30d024461a24f9

nix:
  enable: true
  packages: [ zlib, pkgconfig, pcre, mysql, cacert ]
