name: web-browser
version: '0.1.0.0'
category: Web
author: Carl Eyeinsky
maintainer: eyeinsky9@gmail.com
license: MIT
default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- InstanceSigs
dependencies:
- base
- bytestring
- text
- lens
library:
  exposed-modules:
  - Web.Browser
